
package ui.custom;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.border.Border;


public class ItemUI extends javax.swing.JPanel {

    private Color borderColor;
    //private String foodType;
    
    public ItemUI(String foodType, String name, float price) {
        initComponents();
        
        this.setPreferredSize(new Dimension(425, 76));
        
        foodNameTxt.setText(name);
        
        priceTxt.setText("₱"+String.format("%.2f", price));
        setBorderColor(foodType);
    }
    
    private void setBorderColor(String foodType) {
        switch(foodType) {
            case "Breakfast":
                borderColor = Color.decode("#ffd43b");
                break;
            case "Lunch":
                borderColor = Color.decode("#ff9430");
                break;
            case "Dinner":
                borderColor = Color.decode("#7b3dff");
                break;
            case "Dessert":
                borderColor = Color.decode("#ecadff");
                break;
            case "Drink":
                borderColor = Color.decode("#24e3ed");
                break;
        }
        
        Border newBorder = BorderFactory.createLineBorder(borderColor, 3);
        this.setBorder(newBorder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodNameTxt = new javax.swing.JLabel();
        priceTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));

        foodNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        foodNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        foodNameTxt.setText("Food Name");

        priceTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        priceTxt.setForeground(new java.awt.Color(255, 255, 255));
        priceTxt.setText("₱99999.99");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(foodNameTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodNameTxt;
    private javax.swing.JLabel priceTxt;
    // End of variables declaration//GEN-END:variables
}
