package ui.custom;

public class OrderItemPanel extends javax.swing.JPanel {

    public OrderItemPanel(String foodType, String name, float price) {
        initComponents();
        
        //i set ang item information
        foodNameTxt.setText(name);
        priceTxt.setText("₱"+String.format("%.2f", price));
    }
    
    //mag return ug total price
    public float getTotalPrice() {
        //kuhaon ang total price which is price * quantity
        float price = Float.parseFloat(priceTxt.getText());
        int qty = Integer.parseInt(qtyTxt.getText());
        float total = price * qty;
        
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodNameTxt = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JLabel();
        reduceBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        priceTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(33, 33, 33));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));

        foodNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        foodNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        foodNameTxt.setText("Food Name");

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 255, 255));
        jlabel.setText("Price: ₱");

        qtyTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qtyTxt.setForeground(new java.awt.Color(255, 255, 255));
        qtyTxt.setText("Qty: 999");

        reduceBtn.setBackground(new java.awt.Color(66, 66, 66));
        reduceBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reduceBtn.setForeground(new java.awt.Color(255, 255, 255));
        reduceBtn.setText("-");
        reduceBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 66), 3));

        removeBtn.setBackground(new java.awt.Color(66, 66, 66));
        removeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        removeBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeBtn.setText("X");
        removeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 66, 66), 3));

        priceTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        priceTxt.setForeground(new java.awt.Color(255, 255, 255));
        priceTxt.setText(" 99999.99");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(foodNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(reduceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(foodNameTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel)
                            .addComponent(priceTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reduceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel foodNameTxt;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel priceTxt;
    private javax.swing.JLabel qtyTxt;
    private javax.swing.JButton reduceBtn;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
